### PR TITLE
increase size of new PyPI banner

### PR DESCRIPTION
**Pull request by lgh2**
Increases the size of the banner that redirects users to the PSF blog post about Warehouse.

### CODE REVIEW

**Comment by brainwane** [comment]
I looked at this on Laura's machine and it looked fine. :)

**Comment by ewdurbin** [comment]
just using chrome dev tools... this doesn't seem to act nicely.
screen shot 2018-03-01 at 6 12 37 pm
screen shot 2018-03-01 at 6 12 40 pm

**Comment by ewdurbin** [comment]
even reducing the font-size to `1em` doesn't really handle narrow screens well.

screen shot 2018-03-01 at 6 15 17 pm
screen shot 2018-03-01 at 6 15 13 pm

**Comment by ewdurbin** [comment]
I'm not in favor of increasing the size. The selected size was specifically to keep from blowing up the UI on narrow screens. 
screen shot 2018-03-01 at 6 16 23 pm

**Comment by ewdurbin** [comment]
@lgh2 any desire to see this through?

**Comment by brainwane** [comment]
@lgh2 I'm exercising my judgment and closing this, but thanks for running the experiment. :)

**Pull request closed without merging**
